name: Spring-mongo-workflow
on: 
  push:
    branches:
      - master
jobs:
  run-java-script:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: aravind2389-springboot
      PROJECT_ID: demoproject-312207
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging

      - uses: google-github-actions/auth@v2
        with: 
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker
        uses: docker/login-action@v2
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        
      - name: Build and push Docker images
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker images 

      - name: Configure Docker Client
        run: |
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker us-docker.pkg.dev --quiet
          gcloud config list

      - name: Push Docker Image to Container Registry (GCR)
        env:
          GIT_TAG: v1
        run: |-
          docker tag $IMAGE_NAME:latest gcr.io/${{ env.PROJECT_ID }}/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest gcr.io/${{ env.PROJECT_ID }}/$IMAGE_NAME:$GIT_TAG
          docker push gcr.io/${{ env.PROJECT_ID }}/$IMAGE_NAME:latest
          docker push gcr.io/${{ env.PROJECT_ID }}/$IMAGE_NAME:$GIT_TAG
          docker images 
