name: Spring-mongo-workflow
on: 
  push:
    branches:
      - master
jobs:
  run-java-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
          
  build-image:
    runs-on: ubuntu-latest
    needs: run-java-script
    steps:
      - name: Build and push Docker images
      - run: docker build -t aravin2389/springboot-mongo:latest .
      
